# To see all available linters: https://golangci-lint.run/usage/linters/
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - asciicheck  # Simple linter to check that your code does not contain non-ASCII identifiers
    - bodyclose   # Checks whether HTTP response body is closed successfully
    - dupl        # Tool for code clone detection
    - errname
    - cyclop      # Checks function and package cyclomatic complexity
linters-settings:
  cyclop:
    skip-tests: true
    max-complexity: 10
    package-average: 0
