repos:
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: pretty-format-golang
        args:
          - --autofix
  
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.47.2
    hooks:
      - id: golangci-lint
        entry: golangci-lint run
        args:
          - --max-issues-per-linter=0
          - --max-same-issues=0
          - --config=.golangci.yaml
          - --new-from-rev=HEAD~1 # comment this arg if you want to run pre-commit run --all-files
  - repo: local
    hooks:
      - id: golang-clean-tests
        name: Go Clean Tests
        entry: go clean -testcache
        pass_filenames: false
        types: [go]
        language: system

      - id: golang-unit-tests
        name: Go Unit Tests
        entry: go test ./... -covermode=atomic -coverprofile=/tmp/coverage.out -coverpkg=./... -count=1	
        pass_filenames: false
        types: [go]
        language: system
