version: '3.0'

services:

  pg-test-db:
    image:  postgres:15.4
    container_name: pg-test-db
    environment:
      - POSTGRES_DB=test-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432

  mysql-test-db:
    image: mysql:8.0
    container_name: mysql-test-db
    environment:
      - MYSQL_DATABASE=test-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=qwerty
      - MYSQL_ROOT_PASSWORD=qwerty
    ports:
      - 3306:3306