name: gocore-ci-tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-22.04
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v4
          with:
            node-version: '1.19'
        - run: go install github.com/mcubik/goverreport@latest
        - run: go mod tidy
        - run: go test ./... -covermode=atomic -coverprofile=/tmp/coverage.out -coverpkg=./... -count=1
        - run: goverreport -coverprofile=/tmp/coverage.out -sort=block -order=desc -threshold=80 || (echo -e "**********Minimum test coverage was not reached(80%)**********"; exit 1)